[profile.default]
src = 'src'
out = 'out'
libs = ['lib']

# we want gas reports
gas_reports = ["*"]
optimizer = true
optimizer_runs = 20000
# Remappings in remappings.txt

# See more config options https://github.com/foundry-rs/foundry/tree/master/config